name: NodeCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: 5

      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop

      - name: Setup MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          mariadb version: '10.5.19'
          mysql root password: ''
          mysql database: 'jsdelivr-stats-test'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true
